In [ ]:
import pandas as pd

# Load the CSV file
csv_file = '/content/individual_test_solutions.csv'

# Read the CSV into a DataFrame
df = pd.read_csv(csv_file)

# Show the first few rows to verify the data
print(df.head())

   sr                                               link  \
0   1  https://www.shl.com/solutions/products/product...
1   2  https://www.shl.com/solutions/products/product...
2   3  https://www.shl.com/solutions/products/product...
3   4  https://www.shl.com/solutions/products/product...
4   5  https://www.shl.com/solutions/products/product...

                              title  \
0  Global Skills Development Report
1                .NET Framework 4.5
2                    .NET MVC (New)
3                   .NET MVVM (New)
4                    .NET WCF (New)

                                         description       languages time  \
0  This report is designed to be given to individ...             NaN  NaN
1  The.NET Framework 4.5 test measures knowledge ...  English (USA),   30
2  Multi-choice test that measures the knowledge ...  English (USA),   17
3  Multi-choice test that measures the knowledge ...  English (USA),    5
4  Multi-choice test that measures the knowledge ...  English (USA),   11

               test remote                                           download  \
0  A, E, B, C, D, P    Yes  https://service.shl.com/docs/Global Skills Dev...
1                 K    Yes  https://service.shl.com/docs/Fact_Sheet-dotnet...
2                 K    Yes    https://service.shl.com/docs/.NET MVC (New).pdf
3                 K    Yes   https://service.shl.com/docs/.NET MVVM (New).pdf
4                 K    Yes    https://service.shl.com/docs/.NET WCF (New).pdf

  adaptive_irt
0      Unknown
1          Yes
2      Unknown
3      Unknown
4      Unknown

In [ ]:
# Example: Test column has "A, C, P"
def expand_test_types(df):
    categories = {
        'A': 'Ability & Aptitude',
        'B': 'Biodata & Situational Judgement',
        'C': 'Competencies',
        'D': 'Development & 360',
        'E': 'Assessment Exercises',
        'K': 'Knowledge & Skills',
        'P': 'Personality & Behavior',
        'S': 'Simulations'
    }

    for key, name in categories.items():
        df[name] = df['test'].apply(lambda x: int(key in str(x)))
    return df

In [ ]:
print(df.columns.tolist())

['sr', 'link', 'title', 'description', 'languages', 'time', 'test', 'remote', 'download', 'adaptive_irt']

In [ ]:
df = expand_test_types(df)
df.head()

,sr,link,title,description,languages,time,test,remote,download,adaptive_irt,Ability & Aptitude,Biodata & Situational Judgement,Competencies,Development & 360,Assessment Exercises,Knowledge & Skills,Personality & Behavior,Simulations
0,1,https://www.shl.com/solutions/products/product...,Global Skills Development Report,This report is designed to be given to individ...,NaN,NaN,"A, E, B, C, D, P",Yes,https://service.shl.com/docs/Global Skills Dev...,Unknown,1,1,1,1,1,0,1,0
1,2,https://www.shl.com/solutions/products/product...,.NET Framework 4.5,The.NET Framework 4.5 test measures knowledge ...,"English (USA),",30,K,Yes,https://service.shl.com/docs/Fact_Sheet-dotnet...,Yes,0,0,0,0,0,1,0,0
2,3,https://www.shl.com/solutions/products/product...,.NET MVC (New),Multi-choice test that measures the knowledge ...,"English (USA),",17,K,Yes,https://service.shl.com/docs/.NET MVC (New).pdf,Unknown,0,0,0,0,0,1,0,0
3,4,https://www.shl.com/solutions/products/product...,.NET MVVM (New),Multi-choice test that measures the knowledge ...,"English (USA),",5,K,Yes,https://service.shl.com/docs/.NET MVVM (New).pdf,Unknown,0,0,0,0,0,1,0,0
4,5,https://www.shl.com/solutions/products/product...,.NET WCF (New),Multi-choice test that measures the knowledge ...,"English (USA),",11,K,Yes,https://service.shl.com/docs/.NET WCF (New).pdf,Unknown,0,0,0,0,0,1,0,0

In [ ]:
df['adaptive_irt'] = df['adaptive_irt'].replace('Unknown', 'No')
print(df['adaptive_irt'].value_counts())

adaptive_irt
No     340
Yes     37
Name: count, dtype: int64

In [ ]:

# Show column-wise null value counts
print("\n🔍 Null Value Count per Column:")
print(df.isnull().sum())

# Show total number of rows
print(f"\n📊 Total Rows: {len(df)}")

# Show unique values in each column
print("\n🔎 Unique Values per Column:")
for col in df.columns:
    print(f"- {col} ({df[col].dtype}):")
    print(df[col].unique()[:5])  # Show first 5 unique values only
    print()

# Show data types and non-null counts
print("\n🧾 DataFrame Info:")
print(df.info())

# Optional: Show descriptive statistics for numeric/time columns
print("\n📈 Descriptive Stats:")
print(df.describe(include='all'))

🔍 Null Value Count per Column:
sr                                  0
link                                0
title                               0
description                         0
languages                          36
time                               61
test                                0
remote                              0
download                           12
adaptive_irt                        0
Ability & Aptitude                  0
Biodata & Situational Judgement     0
Competencies                        0
Development & 360                   0
Assessment Exercises                0
Knowledge & Skills                  0
Personality & Behavior              0
Simulations                         0
dtype: int64

📊 Total Rows: 377

🔎 Unique Values per Column:
- sr (int64):
[1 2 3 4 5]

- link (object):
['https://www.shl.com/solutions/products/product-catalog/view/global-skills-development-report/'
 'https://www.shl.com/solutions/products/product-catalog/view/net-framework-4-5/'
 'https://www.shl.com/solutions/products/product-catalog/view/net-mvc-new/'
 'https://www.shl.com/solutions/products/product-catalog/view/net-mvvm-new/'
 'https://www.shl.com/solutions/products/product-catalog/view/net-wcf-new/']

- title (object):
['Global Skills Development Report' '.NET Framework 4.5' '.NET MVC (New)'
 '.NET MVVM (New)' '.NET WCF (New)']

- description (object):
['This report is designed to be given to individuals who have completed the Global Skills Assessment (GSA). With coverage across the Great 8 Domains, this measure of self-reported behaviors offers a complete overview of their current skills. Participants receive actionable tips on leveraging their top skill strengths and how they might develop their growth skills.'
 'The.NET Framework 4.5 test measures knowledge of .NET environment. Designed for experienced users, this test covers the following topics: Application Development, Application Foundation, Data Modeling, Deployment, Diagnostics, Performance, Portability, and Security.'
 'Multi-choice test that measures the knowledge of Model-View-Controller (MVC) architecture, validation, security, routing, and areas.'
 'Multi-choice test that measures the knowledge of MVVM pattern, scenarios, data validation, ViewModel communication and Quick-start.'
 'Multi-choice test that measures the knowledge of .NET fundamentals, WCF architecture, programming model, SOA, managing and programming WCF.']

- languages (object):
[nan 'English (USA),' 'English International, English (USA),'
 'English (USA), English (Australia), English (Canada), English International, English (South Africa),'
 'French (Canada), Portuguese (Brazil), Dutch, Italian, Spanish, French, Latin American Spanish, Chinese Simplified, English (Australia), English International, English (USA),']

- time (object):
[nan '30' '17' '5' '11']

- test (object):
['A, E, B, C, D, P' 'K' 'S' 'P' 'E']

- remote (object):
['Yes']

- download (object):
['https://service.shl.com/docs/Global Skills Development Report International English.pdf'
 'https://service.shl.com/docs/Fact_Sheet-dotnet_framework_4.5.pdf'
 'https://service.shl.com/docs/.NET MVC (New).pdf'
 'https://service.shl.com/docs/.NET MVVM (New).pdf'
 'https://service.shl.com/docs/.NET WCF (New).pdf']

- adaptive_irt (object):
['No' 'Yes']

- Ability & Aptitude (int64):
[1 0]

- Biodata & Situational Judgement (int64):
[1 0]

- Competencies (int64):
[1 0]

- Development & 360 (int64):
[1 0]

- Assessment Exercises (int64):
[1 0]

- Knowledge & Skills (int64):
[0 1]

- Personality & Behavior (int64):
[1 0]

- Simulations (int64):
[0 1]


🧾 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   sr                               377 non-null    int64
 1   link                             377 non-null    object
 2   title                            377 non-null    object
 3   description                      377 non-null    object
 4   languages                        341 non-null    object
 5   time                             316 non-null    object
 6   test                             377 non-null    object
 7   remote                           377 non-null    object
 8   download                         365 non-null    object
 9   adaptive_irt                     377 non-null    object
 10  Ability & Aptitude               377 non-null    int64
 11  Biodata & Situational Judgement  377 non-null    int64
 12  Competencies                     377 non-null    int64
 13  Development & 360                377 non-null    int64
 14  Assessment Exercises             377 non-null    int64
 15  Knowledge & Skills               377 non-null    int64
 16  Personality & Behavior           377 non-null    int64
 17  Simulations                      377 non-null    int64
dtypes: int64(9), object(9)
memory usage: 53.1+ KB
None

📈 Descriptive Stats:
                sr                                               link  \
count   377.000000                                                377
unique         NaN                                                377
top            NaN  https://www.shl.com/solutions/products/product...
freq           NaN                                                  1
mean    189.000000                                                NaN
std     108.974768                                                NaN
min       1.000000                                                NaN
25%      95.000000                                                NaN
50%     189.000000                                                NaN
75%     283.000000                                                NaN
max     377.000000                                                NaN

                                         title  \
count                                      377
unique                                     377
top     360° Multi-Rater Feedback System (MFS)
freq                                         1
mean                                       NaN
std                                        NaN
min                                        NaN
25%                                        NaN
50%                                        NaN
75%                                        NaN
max                                        NaN

                                              description       languages  \
count                                                 377             341
unique                                                351              75
top     Managerial Scenarios is a unique test of Manag...  English (USA),
freq                                                    4             256
mean                                                  NaN             NaN
std                                                   NaN             NaN
min                                                   NaN             NaN
25%                                                   NaN             NaN
50%                                                   NaN             NaN
75%                                                   NaN             NaN
max                                                   NaN             NaN

       time test remote                                           download  \
count   316  377    377                                                365
unique   37   27      1                                                354
top      10    K    Yes  https://service.shl.com/docs/Language Assessme...
freq     34  229    377                                                 10
mean    NaN  NaN    NaN                                                NaN
std     NaN  NaN    NaN                                                NaN
min     NaN  NaN    NaN                                                NaN
25%     NaN  NaN    NaN                                                NaN
50%     NaN  NaN    NaN                                                NaN
75%     NaN  NaN    NaN                                                NaN
max     NaN  NaN    NaN                                                NaN

       adaptive_irt  Ability & Aptitude  Biodata & Situational Judgement  \
count           377          377.000000                       377.000000
unique            2                 NaN                              NaN
top              No                 NaN                              NaN
freq            340                 NaN                              NaN
mean            NaN            0.084881                         0.045093
std             NaN            0.279074                         0.207784
min             NaN            0.000000                         0.000000
25%             NaN            0.000000                         0.000000
50%             NaN            0.000000                         0.000000
75%             NaN            0.000000                         0.000000
max             NaN            1.000000                         1.000000

        Competencies  Development & 360  Assessment Exercises  \
count     377.000000         377.000000            377.000000
unique           NaN                NaN                   NaN
top              NaN                NaN                   NaN
freq             NaN                NaN                   NaN
mean        0.050398           0.018568              0.005305
std         0.219055           0.135172              0.072739
min         0.000000           0.000000              0.000000
25%         0.000000           0.000000              0.000000
50%         0.000000           0.000000              0.000000
75%         0.000000           0.000000              0.000000
max         1.000000           1.000000              1.000000

        Knowledge & Skills  Personality & Behavior  Simulations
count           377.000000              377.000000   377.000000
unique                 NaN                     NaN          NaN
top                    NaN                     NaN          NaN
freq                   NaN                     NaN          NaN
mean              0.636605                0.175066     0.114058
std               0.481616                0.380529     0.318305
min               0.000000                0.000000     0.000000
25%               0.000000                0.000000     0.000000
50%               1.000000                0.000000     0.000000
75%               1.000000                0.000000     0.000000
max               1.000000                1.000000     1.000000

In [ ]:
# Fill missing values
df['languages'] = df['languages'].fillna('NA')
df['time'] = df['time'].fillna(0)  # Assuming 0 means untimed
df['download'] = df['download'].fillna('NA')

# Checking the result
print(df[['languages', 'time', 'download']].isnull().sum())

languages    0
time         0
download     0
dtype: int64

In [ ]:
# Print unique values and their counts for each column
for column in df.columns:
    print(f"Unique values and counts for '{column}':")
    print(df[column].value_counts())
    print("\n" + "-"*50 + "\n")

Unique values and counts for 'sr':
sr
377    1
1      1
2      1
3      1
4      1
      ..
14     1
13     1
12     1
11     1
10     1
Name: count, Length: 377, dtype: int64

--------------------------------------------------

Unique values and counts for 'link':
link
https://www.shl.com/solutions/products/product-catalog/view/360-multi-rater-feedback-system-mfs/    1
https://www.shl.com/solutions/products/product-catalog/view/global-skills-development-report/       1
https://www.shl.com/solutions/products/product-catalog/view/net-framework-4-5/                      1
https://www.shl.com/solutions/products/product-catalog/view/net-mvc-new/                            1
https://www.shl.com/solutions/products/product-catalog/view/net-mvvm-new/                           1
                                                                                                   ..
https://www.shl.com/solutions/products/product-catalog/view/adobe-photoshop-cc/                     1
https://www.shl.com/solutions/products/product-catalog/view/adobe-experience-manager-new/           1
https://www.shl.com/solutions/products/product-catalog/view/ado-net-new/                            1
https://www.shl.com/solutions/products/product-catalog/view/accounts-receivable-simulation-new/     1
https://www.shl.com/solutions/products/product-catalog/view/accounts-receivable-new/                1
Name: count, Length: 377, dtype: int64

--------------------------------------------------

Unique values and counts for 'title':
title
360° Multi-Rater Feedback System (MFS)    1
Global Skills Development Report          1
.NET Framework 4.5                        1
.NET MVC (New)                            1
.NET MVVM (New)                           1
                                         ..
Adobe Photoshop CC                        1
Adobe Experience Manager (New)            1
ADO.NET (New)                             1
Accounts Receivable Simulation (New)      1
Accounts Receivable (New)                 1
Name: count, Length: 377, dtype: int64

--------------------------------------------------

Unique values and counts for 'description':
description
Managerial Scenarios is a unique test of Managerial Judgement - an individual’s ability to decide on effective ways of handling real life situations. It consists of hypothetical scenarios, each followed by several possible responses. Candidates rate the effectiveness of each response, using a 6-point scale, from highly undesirable to highly desirable. It can be used for recruitment, selection, training and development, performance management and coaching in a variety of functions and industries.\r\n\r\nReports available:\r\n\r\nManagement Scenarios Narrative Report:  A participant focused report that contains;  \r\n - Management Scenarios profile\r\n - Detailed narrative feedback of each of the 4 scales;  Managerial Judgement, Managing Objectives, People Management and Reputation Management.\r\n - Table of scores for each of the 6 style scales;  Big picture, Delegative, One-to-one, Team, Personal recognition and Company Protocol.\r\n - Detailed narrative feedback report (with development tips) for each of the 6 style scales.\r\n\r\nManagement Scenarios Candidate Report:  A report to share with the candidate that contains: \r\n - Detailed narrative feedback of each of the 4 scales;  Managerial Judgement, Managing Objectives, People Management and Reputation Management.\r\n - Table of scores for each of the 6 style scales;  Big picture, Delegative, One-to-one, Team, Personal recognition and Company Protocol.\r\n - Detailed narrative feedback report (with development tips) for each of the 6 style scales.\r\n\r\nManagement Scenarios Profile:  Displays all scores on these scales in terms of four types of norm system; T-scores, Percentiles, Stens and Grades.    4
An automated spoken English test that measures fluency, pronunciation, active listening, vocabulary, grammar and spoken English understanding.Your use of this assessment product may be subject to New York City Law 144 (Regulation of the Use of Automated Employment Decision Tools) (dated July 5, 2023). Compliance with Law 144 is your responsibility.\r\nRead more on https://www.shl.com/legal/shl-us-regulatory-compliance/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              4
Using the Apta™ Architecture to focus on the relevant competency behaviors in the Universal Competency Framework, SHL developed the RemoteWorkQ to measure self-reported behavioral tendencies in competency areas that are important to performing effectively in remote work environments across three competency areas: \r\no\tWork Relationships\r\no\tWork Habits\r\no\tSelf-Development & Well-Being\r\nThe RemoteWorkQ is intended for use across job families and levels for which working in a remote environment is important for the role. This report is designed to help you be more successful in a remote working environment by providing:\r\no\tInsights into your identified strengths and potential risks for working remotely\r\no\tIndividualized coaching tips on how you can use your identified strengths to overcome risks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
Open response test that evaluates the ability to write proper emails in English. The test provides scores on content, grammar and email etiquette.Your use of this assessment product may be subject to New York City Law 144 (Regulation of the Use of Automated Employment Decision Tools) (dated July 5, 2023). Compliance with Law 144 is your responsibility.\r\nRead more on https://www.shl.com/legal/shl-us-regulatory-compliance/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
Executive Scenarios is a unique test of Managerial Judgement - an individual’s ability to decide on effective ways of handling real life situations. It is specifically designed to assess judgement in Executives; a group who typically has significant work experience to draw on. It consists of hypothetical scenarios, each followed by several possible responses. Candidates rate the effectiveness of each response, using a 6-point scale, from highly undesirable to highly desirable. It can be used for recruitment, selection, training and development, performance management and coaching in a variety of functions and industries.\r\n\r\nReports available: \r\n\r\nExecutive Scenarios Narrative Report:  A participant focused report that contains;  \r\n - Executive Scenarios profile\r\n - VERY detailed narrative feedback of each of the 4 scales;  Managerial Judgement, Managing Objectives, People Management and Reputation Management.\r\n - Development tips for each of the 6 style scales;  Leading and Managing the work, Using external help, One-to-one, Workforce, Organisational support, Commercial support.\r\n\r\nExecutive Scenarios Profile: Displays all scores on these scales in terms of four types of norm system; T-scores, Percentiles, Stens and Grades.                                                                                                                                                                                                                                                                                                                                                                                                                                       3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
Multi-choice test that measures the knowledge of physical chemistry, inorganic chemistry and organic chemistry.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Multi-choice test that measures the knowledge of front office operations.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Multi-choice test that measures the knowledge of food chemistry, nutrition, food microbiology, food engineering and food product technology.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Multi-choice test that measures the knowledge of meal planning, service preparation, types of service equipment, and types of beverages.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1

In [ ]:
# Replace unwanted time values with 0
df['time'] = df['time'].replace([
    'Approximate Completion Time in minutes = Untimed',
    'Approximate Completion Time in minutes = -',
    'Approximate Completion Time in minutes = Variable',
    'Approximate Completion Time in minutes = TBC',
    'Approximate Completion Time in minutes = N/A'
], 0)

# Verify if replacement is done
print(df['time'].value_counts())

time
0     84
10    34
9     27
7     25
8     24
5     19
12    16
15    16
11    14
20    13
30    13
6     12
13    12
35     8
25     8
4      7
17     7
16     6
3      5
60     4
18     4
14     3
19     3
0      2
24     2
36     2
45     1
31     1
49     1
34     1
26     1
2      1
22     1
Name: count, dtype: int64

In [ ]:
df['is_untimed'] = df['time'].apply(lambda x: 1 if x == 0 else 0)

In [ ]:
df.head()

,sr,link,title,description,languages,time,test,remote,download,adaptive_irt,Ability & Aptitude,Biodata & Situational Judgement,Competencies,Development & 360,Assessment Exercises,Knowledge & Skills,Personality & Behavior,Simulations,is_untimed
0,1,https://www.shl.com/solutions/products/product...,Global Skills Development Report,This report is designed to be given to individ...,NA,0,"A, E, B, C, D, P",Yes,https://service.shl.com/docs/Global Skills Dev...,No,1,1,1,1,1,0,1,0,1
1,2,https://www.shl.com/solutions/products/product...,.NET Framework 4.5,The.NET Framework 4.5 test measures knowledge ...,"English (USA),",30,K,Yes,https://service.shl.com/docs/Fact_Sheet-dotnet...,Yes,0,0,0,0,0,1,0,0,0
2,3,https://www.shl.com/solutions/products/product...,.NET MVC (New),Multi-choice test that measures the knowledge ...,"English (USA),",17,K,Yes,https://service.shl.com/docs/.NET MVC (New).pdf,No,0,0,0,0,0,1,0,0,0
3,4,https://www.shl.com/solutions/products/product...,.NET MVVM (New),Multi-choice test that measures the knowledge ...,"English (USA),",5,K,Yes,https://service.shl.com/docs/.NET MVVM (New).pdf,No,0,0,0,0,0,1,0,0,0
4,5,https://www.shl.com/solutions/products/product...,.NET WCF (New),Multi-choice test that measures the knowledge ...,"English (USA),",11,K,Yes,https://service.shl.com/docs/.NET WCF (New).pdf,No,0,0,0,0,0,1,0,0,0

In [ ]:
df['combined_description'] = df['title'] + ' ' + df['description'] + ' ' + df['languages'] + ' ' + df['test'] + ' Untimed: ' + df['is_untimed'].astype(str)

In [ ]:
df.head()

,sr,link,title,description,languages,time,test,remote,download,adaptive_irt,Ability & Aptitude,Biodata & Situational Judgement,Competencies,Development & 360,Assessment Exercises,Knowledge & Skills,Personality & Behavior,Simulations,is_untimed,combined_description
0,1,https://www.shl.com/solutions/products/product...,Global Skills Development Report,This report is designed to be given to individ...,NA,0,"A, E, B, C, D, P",Yes,https://service.shl.com/docs/Global Skills Dev...,No,1,1,1,1,1,0,1,0,1,Global Skills Development Report This report i...
1,2,https://www.shl.com/solutions/products/product...,.NET Framework 4.5,The.NET Framework 4.5 test measures knowledge ...,"English (USA),",30,K,Yes,https://service.shl.com/docs/Fact_Sheet-dotnet...,Yes,0,0,0,0,0,1,0,0,0,.NET Framework 4.5 The.NET Framework 4.5 test ...
2,3,https://www.shl.com/solutions/products/product...,.NET MVC (New),Multi-choice test that measures the knowledge ...,"English (USA),",17,K,Yes,https://service.shl.com/docs/.NET MVC (New).pdf,No,0,0,0,0,0,1,0,0,0,.NET MVC (New) Multi-choice test that measures...
3,4,https://www.shl.com/solutions/products/product...,.NET MVVM (New),Multi-choice test that measures the knowledge ...,"English (USA),",5,K,Yes,https://service.shl.com/docs/.NET MVVM (New).pdf,No,0,0,0,0,0,1,0,0,0,.NET MVVM (New) Multi-choice test that measure...
4,5,https://www.shl.com/solutions/products/product...,.NET WCF (New),Multi-choice test that measures the knowledge ...,"English (USA),",11,K,Yes,https://service.shl.com/docs/.NET WCF (New).pdf,No,0,0,0,0,0,1,0,0,0,.NET WCF (New) Multi-choice test that measures...

In [ ]:
import google.generativeai as genai

# Configure Gemini
genai.configure(api_key="AIzaSyAcFfmOOD48lky8LvIMYJ_1dXlMc5RAIsw")



# Load the embedding model
def get_embedding(text):
    try:
        response = genai.embed_content(
            model="models/embedding-001",
            content=text,
            task_type="retrieval_document"  # or "retrieval_query"
        )
        return response['embedding']
    except Exception as e:
        print(f"Error embedding: {e}")
        return None

# Apply to your DataFrame column
df['gemini_embedding'] = df['combined_description'].apply(get_embedding)

In [ ]:
df.head()

,sr,link,title,description,languages,time,test,remote,download,adaptive_irt,...,Biodata & Situational Judgement,Competencies,Development & 360,Assessment Exercises,Knowledge & Skills,Personality & Behavior,Simulations,is_untimed,combined_description,gemini_embedding
0,1,https://www.shl.com/solutions/products/product...,Global Skills Development Report,This report is designed to be given to individ...,NA,0,"A, E, B, C, D, P",Yes,https://service.shl.com/docs/Global Skills Dev...,No,...,1,1,1,1,0,1,0,1,Global Skills Development Report This report i...,"[0.06945961, -0.018844353, -0.052282188, -0.00..."
1,2,https://www.shl.com/solutions/products/product...,.NET Framework 4.5,The.NET Framework 4.5 test measures knowledge ...,"English (USA),",30,K,Yes,https://service.shl.com/docs/Fact_Sheet-dotnet...,Yes,...,0,0,0,0,1,0,0,0,.NET Framework 4.5 The.NET Framework 4.5 test ...,"[0.045742404, -0.0020624322, -0.055631388, -0...."
2,3,https://www.shl.com/solutions/products/product...,.NET MVC (New),Multi-choice test that measures the knowledge ...,"English (USA),",17,K,Yes,https://service.shl.com/docs/.NET MVC (New).pdf,No,...,0,0,0,0,1,0,0,0,.NET MVC (New) Multi-choice test that measures...,"[0.04154671, -0.011033193, -0.05151112, -0.005..."
3,4,https://www.shl.com/solutions/products/product...,.NET MVVM (New),Multi-choice test that measures the knowledge ...,"English (USA),",5,K,Yes,https://service.shl.com/docs/.NET MVVM (New).pdf,No,...,0,0,0,0,1,0,0,0,.NET MVVM (New) Multi-choice test that measure...,"[-4.63718e-05, -0.0072347266, -0.066985905, 0...."
4,5,https://www.shl.com/solutions/products/product...,.NET WCF (New),Multi-choice test that measures the knowledge ...,"English (USA),",11,K,Yes,https://service.shl.com/docs/.NET WCF (New).pdf,No,...,0,0,0,0,1,0,0,0,.NET WCF (New) Multi-choice test that measures...,"[0.047855146, -0.0008174303, -0.07034179, -0.0..."

In [ ]:
# Save the DataFrame to a CSV file
df.to_csv('/content/embedded_assessments.csv', index=False)